export { default as MenuMain } from './MenuMain';
export { default as SideMenu } from './SideMenu';
export { default as Footer } from './Footer';
export { default as Product } from './Product';
export { default as PrimaryGradientBtn } from './PrimaryGradientBtn';
export { default as Modal } from './Modal';
export { default as Text } from './Text';
export { default as Box } from './Box';
export { default as FlexBox } from './FlexBox';
